// FamilyUi values mirroring config/models.yaml (stickDefault is a 0…1 dial position). Used by the browser mock backend
// and by unit tests only — the real app gets these from `family_ui`.
import type { FamilyUi } from "../types";

const shapes1024: Record<string, [number, number]> = {
  square: [1024, 1024],
  portrait: [832, 1216],
  landscape: [1216, 832],
  wide: [1344, 768],
};
const shapes512: Record<string, [number, number]> = {
  square: [512, 512],
  portrait: [512, 768],
  landscape: [768, 512],
  wide: [912, 512],
};

const base: FamilyUi = {
  familyId: "sdxl",
  label: "SDXL",
  modes: ["txt2img", "img2img", "inpaint"],
  shapes: shapes1024,
  qualitySteps: [20, 30, 40],
  showStick: true,
  stickMapsTo: "cfg",
  stickRange: [3, 9],
  stickDefault: 0.5,
  usesNegativePrompt: true,
  defaultNegativePrompt: "lowres, blurry, bad anatomy, deformed hands, watermark, text",
  defaultSampler: "dpm++2m",
  defaultScheduler: "karras",
  defaultClipSkip: 1,
  defaultFlowShift: null,
  defaultCfg: 6,
  defaultGuidance: null,
  autoPromptPrefix: null,
  hiresAtBest: false,
  licenseNote: null,
  isEditFamily: false,
  stayCloseShown: true,
  stayCloseDefault: 0.5,
};

const FIXTURES: Record<string, FamilyUi> = {
  sd15: {
    ...base,
    familyId: "sd15",
    label: "Stable Diffusion 1.5",
    shapes: shapes512,
    qualitySteps: [15, 25, 35],
    stickRange: [4, 11],
    stickDefault: 3 / 7,
    defaultCfg: 7,
    defaultNegativePrompt: "lowres, blurry, bad anatomy, extra fingers, watermark, text",
    hiresAtBest: true,
    seamless: true,
  },
  sdxl: { ...base, seamless: true },
  sdxl_pony: {
    ...base,
    seamless: true,
    familyId: "sdxl_pony",
    label: "SDXL · Pony",
    stickRange: [4, 8],
    stickDefault: 0.5,
    defaultSampler: "euler_a",
    defaultScheduler: "discrete",
    defaultClipSkip: 2,
    autoPromptPrefix: "score_9, score_8_up, score_7_up, ",
    defaultNegativePrompt: "score_4, score_5, score_6, lowres, bad anatomy",
  },
  sdxl_illustrious: {
    ...base,
    seamless: true,
    familyId: "sdxl_illustrious",
    label: "SDXL · Illustrious / NoobAI",
    stickRange: [4, 8],
    stickDefault: 0.375,
    defaultCfg: 5.5,
    defaultSampler: "euler_a",
    defaultScheduler: "discrete",
    defaultClipSkip: 2,
    autoPromptPrefix: "masterpiece, best quality, ",
    defaultNegativePrompt: "worst quality, low quality, lowres, bad anatomy, bad hands, watermark",
  },
  flux1_dev: {
    ...base,
    familyId: "flux1_dev",
    label: "FLUX.1 dev",
    modes: ["txt2img", "img2img"],
    qualitySteps: [16, 24, 32],
    stickMapsTo: "guidance",
    stickRange: [2, 5],
    stickDefault: 0.5,
    usesNegativePrompt: false,
    defaultNegativePrompt: null,
    defaultSampler: "euler",
    defaultScheduler: "simple",
    defaultClipSkip: null,
    defaultCfg: 1,
    defaultGuidance: 3.5,
    licenseNote: "Non-commercial license",
  },
  flux1_schnell: {
    ...base,
    familyId: "flux1_schnell",
    label: "FLUX.1 schnell",
    modes: ["txt2img", "img2img"],
    qualitySteps: [2, 4, 6],
    stickMapsTo: "guidance",
    stickRange: [2, 5],
    stickDefault: 0.5,
    usesNegativePrompt: false,
    defaultNegativePrompt: null,
    defaultSampler: "euler",
    defaultScheduler: "simple",
    defaultClipSkip: null,
    defaultCfg: 1,
    defaultGuidance: 3.5,
    licenseNote: "Apache 2.0",
  },
  z_image_turbo: {
    ...base,
    familyId: "z_image_turbo",
    label: "Z-Image Turbo",
    modes: ["txt2img", "img2img"],
    qualitySteps: [6, 8, 10],
    showStick: false,
    stickMapsTo: "cfg",
    stickRange: [1, 1],
    stickDefault: 0.5,
    usesNegativePrompt: false,
    defaultNegativePrompt: null,
    defaultSampler: "euler",
    defaultScheduler: "simple",
    defaultClipSkip: null,
    defaultCfg: 1,
    licenseNote: "Apache 2.0",
  },
  qwen_image_edit_2511: {
    ...base,
    familyId: "qwen_image_edit_2511",
    label: "Qwen Image Edit",
    modes: ["edit"],
    qualitySteps: [12, 20, 30],
    stickRange: [1.5, 4],
    stickDefault: 0.6,
    usesNegativePrompt: false,
    defaultNegativePrompt: null,
    defaultSampler: "euler",
    defaultScheduler: null,
    defaultClipSkip: null,
    defaultFlowShift: 3,
    defaultCfg: 2.5,
    isEditFamily: true,
    stayCloseDefault: 0.6,
  },
  flux1_kontext: {
    ...base,
    familyId: "flux1_kontext",
    label: "FLUX.1 Kontext",
    modes: ["edit"],
    qualitySteps: [16, 24, 30],
    stickMapsTo: "guidance",
    stickRange: [1.5, 4],
    stickDefault: 0.6,
    usesNegativePrompt: false,
    defaultNegativePrompt: null,
    defaultSampler: "euler",
    defaultScheduler: null,
    defaultClipSkip: null,
    defaultCfg: 1,
    defaultGuidance: 2.5,
    licenseNote: "Non-commercial license",
    isEditFamily: true,
    stayCloseDefault: 0.6,
  },
};

// Generators edit with the same dial inverted ("Stay close" = low CFG/guidance), like `family_ui`.
export const FAMILY_UI: Record<string, FamilyUi> = Object.fromEntries(
  Object.entries(FIXTURES).map(([id, ui]) => [
    id,
    ui.isEditFamily ? ui : { ...ui, stayCloseShown: ui.showStick, stayCloseDefault: ui.showStick ? 1 - ui.stickDefault : 0.5 },
  ]),
);
